% make a file to convert param names to figure appropriate
function n = convert_paramname(param_name)
    if strcmp(param_name, 'k_PTHg_deg')
        n = 'k_{deg}^{PTHg}';
    elseif strcmp(param_name, 'rho_exo')
        n = '\rho_{exo}';
    elseif strcmp(param_name, 'k_PTHp_deg')
        n = 'k_{deg}^{PTHp}';
    elseif strcmp(param_name, 'Gamma_res_min')
        n = '\Gamma_{res}^{min}';
    elseif strcmp(param_name, 'delta_res_max')
        n = '\delta_{res}^{max}';
    elseif strcmp(param_name, 'kappa_b')
        n = '\kappa_b';
    elseif strcmp(param_name, 'nconv')
        n = 'n_{conv}';
    elseif strcmp(param_name, 'gamma_conv_Ca')
        n = '\gamma_{conv}^{Ca}';
    elseif strcmp(param_name, 'k_deg_D3')
        n = 'k_{deg}^{D3*}';
    elseif strcmp(param_name, 'k_pf_Ca')
        n = 'k_{pf}^{Ca}';
    elseif strcmp(param_name, 'k_fp_Ca')
        n = 'k_{fp}^{Ca}';
    elseif strcmp(param_name, 'Cap_ref')
        n = 'Cap_{ref}';
    elseif strcmp(param_name, 'k_EGTA_on')
        n = 'k_{EGTA}^{on}';
    elseif strcmp(param_name, 'k_EGTA_off')
        n = 'k_{EGTA}^{off}';
    elseif strcmp(param_name, 'Vp')
        n = 'V_p';
    elseif strcmp(param_name, 'gamma_conv_D3')
        n = '\gamma_{conv}^{D3*}';
    elseif strcmp(param_name, 'delta_conv_max')
        n = '\delta_{conv}^{max}';
    elseif strcmp(param_name, 'k_conv_min')
        n = 'k_{conv}^{min}';
    elseif strcmp(param_name, 'D3_inact_p')
        n = '[D_3]_p^{inact}';
    elseif strcmp(param_name, 'gamma_prod_D3')
        n = '\gamma_{prod}^{D3*}';
    elseif strcmp(param_name, 'ICa')
        n = 'I_{Ca}';
    elseif strcmp(param_name, 'Gamma_abs0')
        n = '\Gamma_{abs0}';
    elseif strcmp(param_name, 'delta_abs_D3')
        n = '\delta_{abs}^{D3*}';
    elseif strcmp(param_name, 'K_abs_D3')
        n = 'K_{abs}^{D3*}';
    elseif strcmp(param_name, 'K_D3p_res')
        n = 'K_{res}^{D3*}';
    elseif strcmp(param_name, 'Lambda_PT0')
        n = '\lambda_{PT0}';
    elseif strcmp(param_name, 'delta_PT_max')
        n = '\delta_{PT}^{max}';
    elseif strcmp(param_name, 'Lambda_TAL0')
        n = '\lambda_{TAL0}';
    elseif strcmp(param_name, 'delta_TAL_max')
        n = '\delta_{TAL}^{max}';
    elseif strcmp(param_name, 'delta_DCT_max')
        n = '\delta_{DCT}^{max}';
    elseif strcmp(param_name, 'K_DCT_D3p')
        n = 'K_{DCT}^{D3*}';
    elseif strcmp(param_name, 'Lambda_DCT0')
        n = '\lambda_{DCT0}';
    elseif strcmp(param_name, 'FetusORMilk')
        n = '\Gamma_{x}';
    elseif strcmp(param_name, 'K_Ca_CASR')
        n = 'K_{Ca}^{CASR}';
    elseif strcmp(param_name, 'K_conv_PTH')
        n = 'K_{conv}^{PTH}';
    elseif strcmp(param_name, 'k_prod_PTHg')
        n = 'k_{prod}^{PTHg}';
    elseif strcmp(param_name, 'K_PTHp_res')
        n = 'K_{res}^{PTHp}';
    elseif strcmp(param_name, 'gamma_deg_PTHp')
        n = '\gamma_{deg}^{PTHp}';
    elseif strcmp(param_name, 'PTHp_ref')
        n = 'PTHp_{ref}';
    elseif strcmp(param_name, 'K_TAL_PTHp')
        n = 'K_{TAL}^{PTHp}';
    elseif strcmp(param_name, 'K_DCT_PTHp')
        n = 'K_{DCT}^{PTHp}';
    elseif strcmp(param_name, 'n1_exo')
        n = 'n1_{exo}';
    elseif strcmp(param_name, 'n2_exo')
        n = 'n2_{exo}';
    elseif strcmp(param_name, 'beta_exo_PTHg')
        n = '\beta_{exo}^{PTHg}';
    elseif strcmp(param_name, 'gamma_exo_PTHg')
        n = '\gamma_{exo}^{PTHg}';
    elseif strcmp(param_name, 'Gamma_ac')
        n = '\Gamma_{ac}';
    else
        n = param_name;
    end
end